In [32]:
import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import  accuracy_score
import itertools

In [2]:
PATH_TO_DATA = 'capstone_user_identification'

In [3]:
train_df_400 = pd.read_csv(os.path.join(PATH_TO_DATA,'train_sessions_400users.csv'), 
                           index_col='session_id')
train_df_400.head()

site1                time1    site2                time2    site3  \
session_id                                                                      
1           23713  2014-03-24 15:22:40  23720.0  2014-03-24 15:22:48  23713.0   
2            8726  2014-04-17 14:25:58   8725.0  2014-04-17 14:25:59    665.0   
3             303  2014-03-21 10:12:24     19.0  2014-03-21 10:12:36    303.0   
4            1359  2013-12-13 09:52:28    925.0  2013-12-13 09:54:34   1240.0   
5              11  2013-11-26 12:35:29     85.0  2013-11-26 12:35:31     52.0   

                          time3    site4                time4    site5  \
session_id                                                               
1           2014-03-24 15:22:48  23713.0  2014-03-24 15:22:54  23720.0   
2           2014-04-17 14:25:59   8727.0  2014-04-17 14:25:59     45.0   
3           2014-03-21 10:12:54    303.0  2014-03-21 10:13:01    303.0   
4           2013-12-13 09:54:34   1360.0  2013-12-13 09:54:34   1344.0   
5           2013-11-26 12:35:31     85.0  2013-11-26 12:35:32     11.0   

                          time5  ...                time6    site7  \
session_id                       ...                                 
1           2014-03-24 15:22:54  ...  2014-03-24 15:22:55  23713.0   
2           2014-04-17 14:25:59  ...  2014-04-17 14:26:01     45.0   
3           2014-03-21 10:13:24  ...  2014-03-21 10:13:36    303.0   
4           2013-12-13 09:54:34  ...  2013-12-13 09:54:34   1346.0   
5           2013-11-26 12:35:32  ...  2013-11-26 12:35:32     11.0   

                          time7    site8                time8    site9  \
session_id                                                               
1           2014-03-24 15:23:01  23713.0  2014-03-24 15:23:03  23713.0   
2           2014-04-17 14:26:01   5320.0  2014-04-17 14:26:18   5320.0   
3           2014-03-21 10:13:54    309.0  2014-03-21 10:14:01    303.0   
4           2013-12-13 09:54:34   1345.0  2013-12-13 09:54:34   1344.0   
5           2013-11-26 12:37:03     85.0  2013-11-26 12:37:03     10.0   

                          time9   site10               time10 user_id  
session_id                                                             
1           2014-03-24 15:23:04  23713.0  2014-03-24 15:23:05     653  
2           2014-04-17 14:26:47   5320.0  2014-04-17 14:26:48     198  
3           2014-03-21 10:14:06    303.0  2014-03-21 10:14:24      34  
4           2013-12-13 09:58:19   1345.0  2013-12-13 09:58:19     601  
5           2013-11-26 12:37:03     85.0  2013-11-26 12:37:04     273  

[5 rows x 21 columns]

In [4]:
test_df_400 = pd.read_csv(os.path.join(PATH_TO_DATA,'test_sessions_400users.csv'), 
                           index_col='session_id')
test_df_400.head()

site1                time1   site2                time2   site3  \
session_id                                                                    
1               9  2014-10-04 12:24:43   304.0  2014-10-04 12:25:34   308.0   
2             838  2014-12-02 09:20:37   504.0  2014-12-02 09:20:38    68.0   
3             190  2014-10-01 09:27:38   192.0  2014-10-01 09:27:38     8.0   
4             295  2014-10-02 14:34:17   295.0  2014-10-02 14:34:18   295.0   
5              31  2014-05-19 17:50:21  3177.0  2014-05-19 17:50:21  3174.0   

                          time3    site4                time4  site5  \
session_id                                                             
1           2014-10-04 12:28:33    307.0  2014-10-04 12:28:33   91.0   
2           2014-12-02 09:20:38     11.0  2014-12-02 09:20:38  838.0   
3           2014-10-01 09:27:38    189.0  2014-10-01 09:27:38  191.0   
4           2014-10-02 14:34:19    295.0  2014-10-02 14:34:20  295.0   
5           2014-05-19 17:50:21  32434.0  2014-05-19 17:50:22   27.0   

                          time5  site6                time6   site7  \
session_id                                                            
1           2014-10-04 12:28:33  308.0  2014-10-04 12:28:34   312.0   
2           2014-12-02 09:20:38   11.0  2014-12-02 09:20:40   838.0   
3           2014-10-01 09:27:39  189.0  2014-10-01 09:27:39   190.0   
4           2014-10-02 14:34:21  295.0  2014-10-02 14:34:22   295.0   
5           2014-05-19 17:50:22   31.0  2014-05-19 17:50:22  5698.0   

                          time7   site8                time8   site9  \
session_id                                                             
1           2014-10-04 12:30:31   300.0  2014-10-04 12:31:30   305.0   
2           2014-12-02 09:20:41   886.0  2014-12-02 09:20:42    27.0   
3           2014-10-01 09:27:39  2375.0  2014-10-01 09:27:39   192.0   
4           2014-10-02 14:34:23   295.0  2014-10-02 14:34:24   295.0   
5           2014-05-19 17:50:25  5698.0  2014-05-19 17:50:26  5698.0   

                          time9  site10               time10  
session_id                                                    
1           2014-10-04 12:32:31   309.0  2014-10-04 12:34:31  
2           2014-12-02 09:20:42   305.0  2014-12-02 09:20:42  
3           2014-10-01 09:27:39     8.0  2014-10-01 09:27:39  
4           2014-10-02 14:34:25   295.0  2014-10-02 14:34:26  
5           2014-05-19 17:50:27  4173.0  2014-05-19 17:50:27

In [6]:
y = train_df_400['user_id']
class_encoder = LabelEncoder()
y_for_vw = class_encoder.fit_transform(y) + 1
y_for_vw 

array([262,  82,  16, ..., 254,  91, 256], dtype=int64)

In [7]:
sites = ['site' + str(i) for i in range(1, 11)]

In [8]:
train_share = int(.7 * train_df_400.shape[0])
train_df_part = train_df_400[sites].iloc[:train_share, :]
valid_df = train_df_400[sites].iloc[train_share:, :]

In [9]:
y_train_part_for_vw = y_for_vw[:train_share]
y_valid_for_vw = y_for_vw[train_share:]

Функция для получения vw

In [ ]:
def arrays_to_vw(X, y=None, train=True, out_file='palpatin.vw'):
    
    X = np.array(X,dtype=int)
    if train:
        with open(out_file, 'w') as vw_train_data:         
            for ind,session in enumerate(X): 
                obj = str(y[ind])+' | '+ ' '.join(map(str,session)) + '\n'
                vw_train_data.write(obj)
    else:
        with open(out_file, 'w') as vw_test_data:         
            for ind,session in enumerate(X): 
                obj =  '1 | '+ ' '.join(map(str,session)) + '\n'
                vw_test_data.write(obj)
                
    print('Good, Anakin!')   

Подготовка дополнительных признаков

In [61]:
train_test_df = pd.concat([train_df_400,test_df_400],axis=0,sort=False)
train_test_df

site1                time1    site2                time2    site3  \
session_id                                                                      
1           23713  2014-03-24 15:22:40  23720.0  2014-03-24 15:22:48  23713.0   
2            8726  2014-04-17 14:25:58   8725.0  2014-04-17 14:25:59    665.0   
3             303  2014-03-21 10:12:24     19.0  2014-03-21 10:12:36    303.0   
4            1359  2013-12-13 09:52:28    925.0  2013-12-13 09:54:34   1240.0   
5              11  2013-11-26 12:35:29     85.0  2013-11-26 12:35:31     52.0   
6              83  2014-01-24 14:06:48   1344.0  2014-01-24 14:06:49   1240.0   
7           13585  2013-11-20 14:45:16  13585.0  2013-11-20 14:45:17  13585.0   
8           29312  2013-02-12 08:42:54  29311.0  2013-02-12 08:42:54  29312.0   
9              21  2013-11-16 13:35:17     62.0  2013-11-16 13:35:17     18.0   
10           1563  2014-03-02 13:23:05   1563.0  2014-03-02 13:23:08   1563.0   
11            337  2014-02-13 17:07:11    337.0  2014-02-13 17:07:16    337.0   
12             18  2014-02-04 08:41:26   1105.0  2014-02-04 08:41:26   1635.0   
13            125  2014-02-28 10:49:59   1269.0  2014-02-28 10:49:59    221.0   
14             11  2013-12-18 15:55:05    692.0  2013-12-18 15:55:05    227.0   
15              7  2014-03-20 15:35:27     10.0  2014-03-20 15:35:28     11.0   
16             91  2013-11-12 09:30:59     91.0  2013-11-12 09:31:19     91.0   
17            303  2014-03-21 14:19:58    303.0  2014-03-21 14:20:14    303.0   
18           5443  2014-02-21 14:39:46   5443.0  2014-02-21 14:40:19   5443.0   
19            108  2014-03-28 09:58:14    109.0  2014-03-28 09:58:14    109.0   
20             22  2014-01-15 16:23:37     27.0  2014-01-15 16:23:38   3033.0   
21          19364  2014-04-17 09:14:28   5474.0  2014-04-17 09:14:28   5408.0   
22           3158  2014-03-26 09:44:36   3158.0  2014-03-26 09:44:37   3083.0   
23             52  2014-03-25 16:18:03     11.0  2014-03-25 16:18:03    876.0   
24             10  2014-04-02 16:50:31     44.0  2014-04-02 16:50:31  18770.0   
25            612  2014-01-19 10:19:55    616.0  2014-01-19 10:19:55     17.0   
26            296  2014-03-27 10:32:44    303.0  2014-03-27 10:32:55    303.0   
27             52  2014-04-18 09:19:13     88.0  2014-04-18 09:19:14     89.0   
28           1589  2014-03-24 12:42:03    265.0  2014-03-24 12:42:03   1588.0   
29            697  2014-02-18 18:30:12    697.0  2014-02-18 18:38:37      NaN   
30            310  2014-03-19 15:01:27    311.0  2014-03-19 15:01:27    310.0   
...           ...                  ...      ...                  ...      ...   
46444          27  2014-05-26 11:05:51   4391.0  2014-05-26 11:05:51  33528.0   
46445        6303  2014-05-05 16:34:45      7.0  2014-05-05 16:34:45   1608.0   
46446          11  2014-05-20 15:28:21    875.0  2014-05-20 15:28:42     10.0   
46447        6209  2014-05-26 18:29:20    750.0  2014-05-26 18:29:24     27.0   
46448         181  2014-05-26 17:10:31    183.0  2014-05-26 17:10:40    183.0   
46449        5047  2014-12-02 11:19:22    230.0  2014-12-02 11:19:23   5047.0   
46450       13091  2014-10-02 14:15:22  13091.0  2014-10-02 14:15:23  13091.0   
46451        3291  2014-11-02 13:05:57   1665.0  2014-11-02 13:06:15     36.0   
46452       17134  2014-05-14 10:32:26   1026.0  2014-05-14 10:32:27  17134.0   
46453        5683  2014-12-02 10:54:48   5683.0  2014-12-02 10:54:49    324.0   
46454          10  2014-05-14 12:17:31    553.0  2014-05-14 12:17:32     10.0   
46455           8  2014-10-01 09:29:27    192.0  2014-10-01 09:29:28    192.0   
46456       33684  2014-12-05 13:51:38   5474.0  2014-12-05 13:51:38   5392.0   
46457         313  2014-06-02 13:46:16     40.0  2014-06-02 13:46:17     26.0   
46458         478  2014-05-23 12:26:14    480.0  2014-05-23 12:26:15     81.0   
46459        2805  2014-05-19 16:19:47   2806.0  2014-05-19 16:19:49   2806.0   
46460          27  2014-05-19 12:25:16   62

Время года и день недели начала сессии

In [62]:
season = pd.to_datetime(train_test_df['time1']).apply(lambda x: x.month).apply(lambda x: 1 if x in [12,1,2] else\
                                                                                      (2 if x in [3,4,5] else \
                                                                                      (3 if x in [6,7,8]\
                                                                                      else 4))).values
season

array([2, 2, 2, ..., 4, 4, 3], dtype=int64)

In [63]:
day_of_week = pd.to_datetime(train_test_df['time1']).apply(lambda x:x.weekday()).values
day_of_week

array([0, 3, 4, ..., 6, 1, 4], dtype=int64)

Время просмотра сайтов

In [64]:
from tqdm import tqdm_notebook

In [65]:
train_test_df_time = train_test_df[['time%d' % i for i in range(1, 11)]]
tdf = train_test_df_time.fillna(0)
for i,col in tqdm_notebook(enumerate(tdf.columns)):
    tdf[f'sec{i+1}'] = pd.to_datetime(tdf[col]).apply(lambda x: x.timestamp())
session_times = tdf[['sec%d' % i for i in range(1, 11)]]
session_times.head()

sec1          sec2          sec3          sec4  \
session_id                                                           
1           1.395675e+09  1.395675e+09  1.395675e+09  1.395675e+09   
2           1.397745e+09  1.397745e+09  1.397745e+09  1.397745e+09   
3           1.395397e+09  1.395397e+09  1.395397e+09  1.395397e+09   
4           1.386928e+09  1.386928e+09  1.386928e+09  1.386928e+09   
5           1.385469e+09  1.385469e+09  1.385469e+09  1.385469e+09   

                    sec5          sec6          sec7          sec8  \
session_id                                                           
1           1.395675e+09  1.395675e+09  1.395675e+09  1.395675e+09   
2           1.397745e+09  1.397745e+09  1.397745e+09  1.397745e+09   
3           1.395397e+09  1.395397e+09  1.395397e+09  1.395397e+09   
4           1.386928e+09  1.386928e+09  1.386928e+09  1.386928e+09   
5           1.385469e+09  1.385469e+09  1.385469e+09  1.385469e+09   

                    sec9         sec10  
session_id                              
1           1.395675e+09  1.395675e+09  
2           1.397745e+09  1.397745e+09  
3           1.395397e+09  1.395397e+09  
4           1.386929e+09  1.386929e+09  
5           1.385469e+09  1.385469e+09

In [66]:
for ind, col in enumerate(session_times.columns):
    if ind > 0:
        session_times[f'dur{ind}'] =  session_times[col] - session_times[session_times.columns[ind-1]]
session_times.head()

C:\Users\artem\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


sec1          sec2          sec3          sec4  \
session_id                                                           
1           1.395675e+09  1.395675e+09  1.395675e+09  1.395675e+09   
2           1.397745e+09  1.397745e+09  1.397745e+09  1.397745e+09   
3           1.395397e+09  1.395397e+09  1.395397e+09  1.395397e+09   
4           1.386928e+09  1.386928e+09  1.386928e+09  1.386928e+09   
5           1.385469e+09  1.385469e+09  1.385469e+09  1.385469e+09   

                    sec5          sec6          sec7          sec8  \
session_id                                                           
1           1.395675e+09  1.395675e+09  1.395675e+09  1.395675e+09   
2           1.397745e+09  1.397745e+09  1.397745e+09  1.397745e+09   
3           1.395397e+09  1.395397e+09  1.395397e+09  1.395397e+09   
4           1.386928e+09  1.386928e+09  1.386928e+09  1.386928e+09   
5           1.385469e+09  1.385469e+09  1.385469e+09  1.385469e+09   

                    sec9         sec10   dur1  dur2  dur3  dur4  dur5  dur6  \
session_id                                                                    
1           1.395675e+09  1.395675e+09    8.0   0.0   6.0   0.0   1.0   6.0   
2           1.397745e+09  1.397745e+09    1.0   0.0   0.0   0.0   2.0   0.0   
3           1.395397e+09  1.395397e+09   12.0  18.0   7.0  23.0  12.0  18.0   
4           1.386929e+09  1.386929e+09  126.0   0.0   0.0   0.0   0.0   0.0   
5           1.385469e+09  1.385469e+09    2.0   0.0   1.0   0.0   0.0  91.0   

            dur7   dur8  dur9  
session_id                     
1            2.0    1.0   1.0  
2           17.0   29.0   1.0  
3            7.0    5.0  18.0  
4            0.0  225.0   0.0  
5            0.0    0.0   1.0

In [67]:
durations = session_times[[f'dur{i}' for i in range(1,10)]]
dur_array = np.array(durations,dtype = float)
for i,session in enumerate(dur_array):
    for j,dur in enumerate(session):
        if dur < 0:
            if j==0:
                dur_array[i,j]=30*60
            else:
                dur_array[i,j]=30*60 - sum(session[:j])
pd.DataFrame(dur_array).head()

0     1    2     3     4     5     6      7     8
0    8.0   0.0  6.0   0.0   1.0   6.0   2.0    1.0   1.0
1    1.0   0.0  0.0   0.0   2.0   0.0  17.0   29.0   1.0
2   12.0  18.0  7.0  23.0  12.0  18.0   7.0    5.0  18.0
3  126.0   0.0  0.0   0.0   0.0   0.0   0.0  225.0   0.0
4    2.0   0.0  1.0   0.0   0.0  91.0   0.0    0.0   1.0

In [69]:
train_test_df.shape,dur_array.shape

((229266, 21), (229266, 9))

Количество уникальных сайтов в сессии

In [77]:
train_test_df[sites].head()

site1    site2    site3    site4    site5    site6    site7  \
session_id                                                                
1           23713  23720.0  23713.0  23713.0  23720.0  23713.0  23713.0   
2            8726   8725.0    665.0   8727.0     45.0   8725.0     45.0   
3             303     19.0    303.0    303.0    303.0    303.0    303.0   
4            1359    925.0   1240.0   1360.0   1344.0   1359.0   1346.0   
5              11     85.0     52.0     85.0     11.0     52.0     11.0   

              site8    site9   site10  
session_id                             
1           23713.0  23713.0  23713.0  
2            5320.0   5320.0   5320.0  
3             309.0    303.0    303.0  
4            1345.0   1344.0   1345.0  
5              85.0     10.0     85.0

In [76]:
unique_sites = np.zeros(train_test_df.shape[0],dtype=int)
for i,session in enumerate(train_test_df[sites].values):
    unique_sites[i] = np.unique(session).shape[0]   
        
unique_sites

array([2, 6, 3, ..., 2, 2, 5])

Получение 2 матриц, одна для катигориальных признаков, другая - для вещественных.

In [81]:
shp = (train_test_df.shape[0],1)
Xc = np.hstack([unique_sites.reshape(shp),season.reshape(shp),day_of_week.reshape(shp)])
Xc 

array([[2, 2, 0],
       [6, 2, 3],
       [3, 2, 4],
       ...,
       [2, 4, 6],
       [2, 4, 1],
       [5, 3, 4]], dtype=int64)

In [84]:
Xn = dur_array
Xn

array([[ 8.,  0.,  6., ...,  2.,  1.,  1.],
       [ 1.,  0.,  0., ..., 17., 29.,  1.],
       [12., 18.,  7., ...,  7.,  5., 18.],
       ...,
       [ 1.,  3.,  1., ...,  9.,  2.,  1.],
       [16.,  8.,  1., ..., 30., 30., 30.],
       [ 0., 66., 14., ...,  1.,  1.,  1.]])

Обновленная функция перевода в формат VW

In [95]:
def arrays_to_vw_add_fe(Xs,Xc,Xn, y=None, train=True, out_file='palpatin.vw'):
    
    Xs = np.array(Xs,dtype=int)
    Xc = np.array(Xc)
    Xn = np.array(Xn,dtype=float)
    
    if train:
        with open(out_file, 'w') as vw_train_data:         
            for yy,xs,xc,xn in zip(y,Xs,Xc,Xn): 
                obj = str(yy)+' |session '+ ' '.join(map(str,xs)) +\
                      ' |cat ' + ' '.join([f'Fc{i+1}={val}' for i,val in enumerate(xc)]) +\
                      ' |num ' + ' '.join([f'Fn{i+1}:{val}' for i,val in enumerate(xn)]) + '\n'
                vw_train_data.write(obj)
    else:
        with open(out_file, 'w') as vw_test_data:         
            for xs,xc,xn in zip(Xs,Xc,Xn): 
                obj = '1 |session '+ ' '.join(map(str,xs)) +\
                      ' |cat ' + ' '.join([f'Fc{i+1}={val}' for i,val in enumerate(xc)]) +\
                      ' |num ' + ' '.join([f'Fn{i+1}:{val}' for i,val in enumerate(xn)]) + '\n'
                vw_test_data.write(obj)
                
    print('Good, Anakin, good!')  

Разделение дополнительных матриц

In [87]:
Xc_train= Xc[:182793]
Xc_test = Xc[182793:]

Xn_train= Xn[:182793]
Xn_test = Xn[182793:]

In [88]:
train_share = int(.7 * train_df_400.shape[0])

Xc_train_part = Xc[:train_share, :]
Xc_valid = Xc[train_share:, :]

Xn_train_part = Xn[:train_share, :]
Xn_valid = Xn[train_share:, :]

In [12]:
PATH_TO_DATA2 = 'competition'

Получение сессий vw

In [13]:
%%time
arrays_to_vw(train_df_part.fillna(0).values, y_train_part_for_vw,\
             out_file = os.path.join(PATH_TO_DATA2,'train_part.vw'))
arrays_to_vw(valid_df.fillna(0).values, y_valid_for_vw,\
             out_file = os.path.join(PATH_TO_DATA2,'valid.vw')) 
arrays_to_vw(train_df_400[sites].fillna(0).values, y_for_vw,\
             out_file = os.path.join(PATH_TO_DATA2,'train.vw'))
arrays_to_vw(test_df_400[sites].fillna(0).values,\
             train = False, out_file = os.path.join(PATH_TO_DATA2,'test.vw'))  

Good, Anakin!
Good, Anakin!
Good, Anakin!
Good, Anakin!
Wall time: 9.63 s


In [17]:
!head -4 $PATH_TO_DATA2/train_part.vw

262 | 23713 23720 23713 23713 23720 23713 23713 23713 23713 23713
82 | 8726 8725 665 8727 45 8725 45 5320 5320 5320
16 | 303 19 303 303 303 303 303 309 303 303
241 | 1359 925 1240 1360 1344 1359 1346 1345 1344 1345


In [18]:
!head -4 $PATH_TO_DATA2/valid.vw

4 | 7 923 923 923 11 924 7 924 838 7
160 | 91 198 11 11 302 91 668 311 310 91
312 | 27085 848 118 118 118 118 11 118 118 118
143 | 14919 14919 14917 14918 14917 14918 14917 14918 875 14918


In [19]:
!head -4 $PATH_TO_DATA2/train.vw

262 | 23713 23720 23713 23713 23720 23713 23713 23713 23713 23713
82 | 8726 8725 665 8727 45 8725 45 5320 5320 5320
16 | 303 19 303 303 303 303 303 309 303 303
241 | 1359 925 1240 1360 1344 1359 1346 1345 1344 1345


In [20]:
!head -4 $PATH_TO_DATA2/test.vw

1 | 9 304 308 307 91 308 312 300 305 309
1 | 838 504 68 11 838 11 838 886 27 305
1 | 190 192 8 189 191 189 190 2375 192 8
1 | 295 295 295 295 295 295 295 295 295 295


In [36]:
train_part_vw = os.path.join(PATH_TO_DATA2, 'train_part.vw')
valid_vw = os.path.join(PATH_TO_DATA2, 'valid.vw')
train_vw = os.path.join(PATH_TO_DATA2, 'train.vw')
test_vw = os.path.join(PATH_TO_DATA2, 'test.vw')
model = os.path.join(PATH_TO_DATA2, 'vw_model.vw')
valid_pred = os.path.join(PATH_TO_DATA2,'vw_valid_pred.csv')
pred = os.path.join(PATH_TO_DATA2, 'vw_pred.csv')

In [27]:
!vw --oaa 400 --passes 3 -c -k -b 26 --random_seed 17 -d $train_part_vw -f $model --quiet
!vw -i $model -t -d $valid_vw -p $valid_pred --quiet
print('Done')

Done


In [29]:
valid_pred1 = pd.read_csv(valid_pred,header=None)
valid_pred1.head()

0
0  188
1  220
2  364
3  143
4  132

In [30]:
accuracy_score(y_valid_for_vw,valid_pred1)

0.34541741128414605

In [33]:
!vw --help



VW options:
  --random_seed arg                     seed random number generator
  --ring_size arg                       size of example ring

Update options:
  -l [ --learning_rate ] arg            Set learning rate
  --power_t arg                         t power value
  --decay_learning_rate arg             Set Decay factor for learning_rate 
                                        between passes
  --initial_t arg                       initial t value
  --feature_mask arg                    Use existing regressor to determine 
                                        which parameters may be updated.  If no
                                        initial_regressor given, also used for 
                                        initial weights.

Weight options:
  -i [ --initial_regressor ] arg        Initial regressor(s)
  --initial_weight arg                  Set all weights to an initial value of 
                                        arg.
  --random_weights arg                  mak

Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = 
num sources = 1


In [37]:
%%time
for (loss, passes, bits) in itertools.product(['squared','logistic','hinge'],[2,3,5],[18,26,30]):
    
    !vw --oaa 400 --passes $passes -c -k -b $bits --loss_function $loss --random_seed 17 -d $train_part_vw -f $model --quiet
    
    !vw -i $model -t -d $valid_vw -p $valid_pred --quiet
    
    
    print(f'Params: {loss} {passes} {bits}, Accuracy: {accuracy_score(y_valid_for_vw,pd.read_csv(valid_pred,header=None))}')
    print('---------------')   
    

Params: squared 2 18, Accuracy: 0.1986031583938145
---------------
Params: squared 2 26, Accuracy: 0.3398920456617674
---------------


internal error: memory allocation failed!
Error:  Failed to allocate weight array with 30 bits: try decreasing -b <bits>


Params: squared 2 30, Accuracy: 0.3398920456617674
---------------
Params: squared 3 18, Accuracy: 0.2037820489441628
---------------
Params: squared 3 26, Accuracy: 0.34541741128414605
---------------


internal error: memory allocation failed!
Error:  Failed to allocate weight array with 30 bits: try decreasing -b <bits>


Params: squared 3 30, Accuracy: 0.34541741128414605
---------------
Params: squared 5 18, Accuracy: 0.20773915897735148
---------------
Params: squared 5 26, Accuracy: 0.34979393850979246
---------------


internal error: memory allocation failed!
Error:  Failed to allocate weight array with 30 bits: try decreasing -b <bits>


Params: squared 5 30, Accuracy: 0.34979393850979246
---------------
Params: logistic 2 18, Accuracy: 0.2332506655968489
---------------
Params: logistic 2 26, Accuracy: 0.3458003574163901
---------------


internal error: memory allocation failed!
Error:  Failed to allocate weight array with 30 bits: try decreasing -b <bits>


Params: logistic 2 30, Accuracy: 0.3458003574163901
---------------
Params: logistic 3 18, Accuracy: 0.23656953207629747
---------------
Params: logistic 3 26, Accuracy: 0.3545898829278967
---------------


internal error: memory allocation failed!
Error:  Failed to allocate weight array with 30 bits: try decreasing -b <bits>


Params: logistic 3 30, Accuracy: 0.3545898829278967
---------------
Params: logistic 5 18, Accuracy: 0.23866661803858638
---------------
Params: logistic 5 26, Accuracy: 0.3610452605857252
---------------


internal error: memory allocation failed!
Error:  Failed to allocate weight array with 30 bits: try decreasing -b <bits>


Params: logistic 5 30, Accuracy: 0.3610452605857252
---------------
Params: hinge 2 18, Accuracy: 0.1411794740873117
---------------
Params: hinge 2 26, Accuracy: 0.32240417228928847
---------------


internal error: memory allocation failed!
Error:  Failed to allocate weight array with 30 bits: try decreasing -b <bits>


Params: hinge 2 30, Accuracy: 0.32240417228928847
---------------
Params: hinge 3 18, Accuracy: 0.1449906998796455
---------------
Params: hinge 3 26, Accuracy: 0.33000838834384916
---------------


internal error: memory allocation failed!
Error:  Failed to allocate weight array with 30 bits: try decreasing -b <bits>


Params: hinge 3 30, Accuracy: 0.33000838834384916
---------------
Params: hinge 5 18, Accuracy: 0.14703307925161385
---------------
Params: hinge 5 26, Accuracy: 0.33279842445019875
---------------


internal error: memory allocation failed!
Error:  Failed to allocate weight array with 30 bits: try decreasing -b <bits>


Params: hinge 5 30, Accuracy: 0.33279842445019875
---------------
Wall time: 29min 21s


По результатам подбора победила logloss с числом проходов 5, количество битов 26. Подберем параметры регуляризации.

In [39]:
%%time
for reg in [1e-10,1e-15,1e-20]:
    
    !vw --oaa 400 --passes 5 -c -k -b 26 --loss_function logistic --l2 $reg --random_seed 17\
    -d $train_part_vw -f $model --quiet
    
    !vw -i $model -t -d $valid_vw -p $valid_pred --quiet
    
    
    print(f'Param reg L2: {reg} , Accuracy: {accuracy_score(y_valid_for_vw,pd.read_csv(valid_pred,header=None))}')
    print('---------------') 

Param reg L2: 1e-10 , Accuracy: 0.36097231846529776
---------------
Param reg L2: 1e-15 , Accuracy: 0.3610452605857252
---------------
Param reg L2: 1e-20 , Accuracy: 0.3610452605857252
---------------
Wall time: 22min 4s


In [40]:
%%time
for reg in [1e-10,1e-15,1e-20]:
    
    !vw --oaa 400 --passes 5 -c -k -b 26 --loss_function logistic --l1 $reg --random_seed 17\
    -d $train_part_vw -f $model --quiet
    
    !vw -i $model -t -d $valid_vw -p $valid_pred --quiet
    
    
    print(f'Param reg L1: {reg} , Accuracy: {accuracy_score(y_valid_for_vw,pd.read_csv(valid_pred,header=None))}')
    print('---------------') 

^C
^C
Param reg L1: 1e-10 , Accuracy: 0.360680549983588
---------------
^C
Param reg L1: 1e-15 , Accuracy: 0.3610452605857252
---------------
Param reg L1: 1e-20 , Accuracy: 0.3610452605857252
---------------
Wall time: 15min 4s


In [41]:
%%time
for reg in [5e-8,1e-9,5e-9,1e-10,2e-10,3e-10,4e-10,5e-10,1e-11]:
    
    !vw --oaa 400 --passes 2 -c -k -b 18 --loss_function logistic --l2 $reg --random_seed 17\
    -d $train_part_vw -f $model --quiet
    
    !vw -i $model -t -d $valid_vw -p $valid_pred --quiet
    
    
    print(f'Param reg L2: {reg} , Accuracy: {accuracy_score(y_valid_for_vw,pd.read_csv(valid_pred,header=None))}')
    print('---------------') 

Param reg L2: 5e-08 , Accuracy: 0.21612750282650717
---------------
Param reg L2: 1e-09 , Accuracy: 0.2333418432473832
---------------
Param reg L2: 5e-09 , Accuracy: 0.23175535212808637
---------------
Param reg L2: 1e-10 , Accuracy: 0.23337831430759692
---------------
Param reg L2: 2e-10 , Accuracy: 0.23341478536781063
---------------
Param reg L2: 3e-10 , Accuracy: 0.2335241985484518
---------------
Param reg L2: 4e-10 , Accuracy: 0.23346949195813121
---------------
Param reg L2: 5e-10 , Accuracy: 0.23350596301834495
---------------
Param reg L2: 1e-11 , Accuracy: 0.23321419453663517
---------------
Wall time: 10min 40s


In [42]:
%%time
for reg in [5e-8,1e-9,5e-9,1e-10,2e-10,3e-10,4e-10,5e-10,1e-11]:
    
    !vw --oaa 400 --passes 2 -c -k -b 18 --loss_function logistic --l1 $reg --random_seed 17\
    -d $train_part_vw -f $model --quiet
    
    !vw -i $model -t -d $valid_vw -p $valid_pred --quiet
    
    
    print(f'Param reg L1: {reg} , Accuracy: {accuracy_score(y_valid_for_vw,pd.read_csv(valid_pred,header=None))}')
    print('---------------') 

Param reg L1: 5e-08 , Accuracy: 0.13997592910025894
---------------
Param reg L1: 1e-09 , Accuracy: 0.23303183923556658
---------------
Param reg L1: 5e-09 , Accuracy: 0.22840001458842407
---------------
Param reg L1: 1e-10 , Accuracy: 0.2334330208979175
---------------
Param reg L1: 2e-10 , Accuracy: 0.23354243407855865
---------------
Param reg L1: 3e-10 , Accuracy: 0.23357890513877239
---------------
Param reg L1: 4e-10 , Accuracy: 0.23346949195813121
---------------
Param reg L1: 5e-10 , Accuracy: 0.23345125642802436
---------------
Param reg L1: 1e-11 , Accuracy: 0.23321419453663517
---------------
Wall time: 11min


In [43]:
%%time
for reg in [1e-1,1e-2,2.5e-10,2.7e-10,2.8e-10,3e-10,3.1e-10,3.2e-10,3.3e-10]:
    
    !vw --oaa 400 --passes 2 -c -k -b 18 --loss_function logistic --l1 $reg --random_seed 17\
    -d $train_part_vw -f $model --quiet
    
    !vw -i $model -t -d $valid_vw -p $valid_pred --quiet
    
    
    print(f'Param reg L1: {reg} , Accuracy: {accuracy_score(y_valid_for_vw,pd.read_csv(valid_pred,header=None))}')
    print('---------------') 

Param reg L1: 0.1 , Accuracy: 0.0014770779386556767
---------------
Param reg L1: 0.01 , Accuracy: 0.0014770779386556767
---------------
Param reg L1: 2.5e-10 , Accuracy: 0.23363361172909297
---------------
Param reg L1: 2.7e-10 , Accuracy: 0.23365184725919982
---------------
Param reg L1: 2.8e-10 , Accuracy: 0.23359714066887924
---------------
Param reg L1: 3e-10 , Accuracy: 0.23357890513877239
---------------
Param reg L1: 3.1e-10 , Accuracy: 0.23357890513877239
---------------
Param reg L1: 3.2e-10 , Accuracy: 0.23354243407855865
---------------
Param reg L1: 3.3e-10 , Accuracy: 0.2335241985484518
---------------
Wall time: 11min 23s


In [44]:
!vw --oaa 400 --passes 5 -c -k -b 26 --loss_function logistic --l1 2.7e-10 --random_seed 17\
    -d $train_part_vw -f $model --quiet
    
!vw -i $model -t -d $valid_vw -p $valid_pred --quiet
    
    
print(f'Param reg L1: {reg} , Accuracy: {accuracy_score(y_valid_for_vw,pd.read_csv(valid_pred,header=None))}')
print('---------------') 

Param reg L1: 3.3e-10 , Accuracy: 0.36047995915241254
---------------


In [45]:
!vw --oaa 400 --passes 5 -c -k -b 26 --loss_function logistic --random_seed 17\
    -d $train_part_vw -f $model --quiet
    
!vw -i $model -t -d $valid_vw -p $valid_pred --quiet
    
    
print(f'Accuracy: {accuracy_score(y_valid_for_vw,pd.read_csv(valid_pred,header=None))}')


Accuracy: 0.3610452605857252


In [51]:
%%time
!vw --oaa 400 --passes 5 -c -k -b 26 --loss_function logistic --random_seed 17\
    -d $train_part_vw -f $model --quiet
    
!vw -i $model -t -d $test_vw -p $pred --quiet

print('Done!')

Done!
Wall time: 6min 41s


In [57]:
!vw --oaa 400 --passes 2 -c -k -b 26 --loss_function logistic --random_seed 17\
    -d $train_part_vw -f $model --quiet --ngram 2 --ngram 1 --ngram 3
    
!vw -i $model -t -d $valid_vw -p $valid_pred --quiet
    
    
print(f'Accuracy: {accuracy_score(y_valid_for_vw,pd.read_csv(valid_pred,header=None))}')

Accuracy: 0.3305007476567344


In [15]:
def write_to_submission_file(predicted_labels, out_file,
                             target='user_id', index_label="session_id"):
    # turn predictions into data frame and save as csv file
    predicted_df = pd.DataFrame(predicted_labels,
                                index = np.arange(1, predicted_labels.shape[0] + 1),
                                columns=[target])
    predicted_df.to_csv(out_file, index_label=index_label)

In [52]:
df_pred = pd.read_csv(pred,header=None)
vw_pred = class_encoder.inverse_transform(df_pred - 1)
vw_pred 

array([224, 149, 946, ..., 656, 656, 179], dtype=int64)

In [53]:
df_pred.head()

0
0   90
1   59
2  372
3  265
4  372

In [54]:
write_to_submission_file(vw_pred, os.path.join(PATH_TO_DATA2, 'vw_400_users_vw_log_part.csv'))

Проверим дополнительные признаки

Получение сессий с дополнительными признаками vw

In [108]:
%%time
arrays_to_vw_add_fe(train_df_part.fillna(0).values, Xc_train_part, Xn_train_part, y_train_part_for_vw,\
             out_file = os.path.join(PATH_TO_DATA2,'train_part_fe.vw'))
arrays_to_vw_add_fe(valid_df.fillna(0).values, Xc_valid, Xn_valid,  train = False,\
             out_file = os.path.join(PATH_TO_DATA2,'valid_fe.vw')) 
arrays_to_vw_add_fe(train_df_400[sites].fillna(0).values,  Xc_train, Xn_train,  y_for_vw,\
             out_file = os.path.join(PATH_TO_DATA2,'train_fe.vw'))
arrays_to_vw_add_fe(test_df_400[sites].fillna(0).values, Xc_test, Xn_test, \
             train = False, out_file = os.path.join(PATH_TO_DATA2,'test_fe.vw'))  

Good, Anakin, good!
Good, Anakin, good!
Good, Anakin, good!
Good, Anakin, good!
Wall time: 22.4 s


In [97]:
!head -4 $PATH_TO_DATA2/train_part_fe.vw

262 |session 23713 23720 23713 23713 23720 23713 23713 23713 23713 23713 |cat Fc1=2 Fc2=2 Fc3=0 |num Fn1:8.0 Fn2:0.0 Fn3:6.0 Fn4:0.0 Fn5:1.0 Fn6:6.0 Fn7:2.0 Fn8:1.0 Fn9:1.0
82 |session 8726 8725 665 8727 45 8725 45 5320 5320 5320 |cat Fc1=6 Fc2=2 Fc3=3 |num Fn1:1.0 Fn2:0.0 Fn3:0.0 Fn4:0.0 Fn5:2.0 Fn6:0.0 Fn7:17.0 Fn8:29.0 Fn9:1.0
16 |session 303 19 303 303 303 303 303 309 303 303 |cat Fc1=3 Fc2=2 Fc3=4 |num Fn1:12.0 Fn2:18.0 Fn3:7.0 Fn4:23.0 Fn5:12.0 Fn6:18.0 Fn7:7.0 Fn8:5.0 Fn9:18.0
241 |session 1359 925 1240 1360 1344 1359 1346 1345 1344 1345 |cat Fc1=7 Fc2=1 Fc3=4 |num Fn1:126.0 Fn2:0.0 Fn3:0.0 Fn4:0.0 Fn5:0.0 Fn6:0.0 Fn7:0.0 Fn8:225.0 Fn9:0.0


In [98]:
!head -4 $PATH_TO_DATA2/valid_fe.vw

4 |session 7 923 923 923 11 924 7 924 838 7 |cat Fc1=5 Fc2=1 Fc3=4 |num Fn1:9.0 Fn2:1.0 Fn3:1.0 Fn4:63.0 Fn5:18.0 Fn6:0.0 Fn7:1.0 Fn8:46.0 Fn9:0.0
160 |session 91 198 11 11 302 91 668 311 310 91 |cat Fc1=7 Fc2=4 Fc3=0 |num Fn1:0.0 Fn2:0.0 Fn3:3.0 Fn4:19.0 Fn5:0.0 Fn6:1.0 Fn7:0.0 Fn8:0.0 Fn9:116.0
312 |session 27085 848 118 118 118 118 11 118 118 118 |cat Fc1=4 Fc2=4 Fc3=2 |num Fn1:4.0 Fn2:16.0 Fn3:1.0 Fn4:2.0 Fn5:1.0 Fn6:0.0 Fn7:1.0 Fn8:1.0 Fn9:5.0
143 |session 14919 14919 14917 14918 14917 14918 14917 14918 875 14918 |cat Fc1=4 Fc2=2 Fc3=2 |num Fn1:1.0 Fn2:0.0 Fn3:0.0 Fn4:1.0 Fn5:1.0 Fn6:0.0 Fn7:1.0 Fn8:1.0 Fn9:0.0


In [99]:
!head -4 $PATH_TO_DATA2/test_fe.vw

1 |session 9 304 308 307 91 308 312 300 305 309 |cat Fc1=9 Fc2=4 Fc3=5 |num Fn1:51.0 Fn2:179.0 Fn3:0.0 Fn4:0.0 Fn5:1.0 Fn6:117.0 Fn7:59.0 Fn8:61.0 Fn9:120.0
1 |session 838 504 68 11 838 11 838 886 27 305 |cat Fc1=7 Fc2=1 Fc3=1 |num Fn1:1.0 Fn2:0.0 Fn3:0.0 Fn4:0.0 Fn5:2.0 Fn6:1.0 Fn7:1.0 Fn8:0.0 Fn9:0.0
1 |session 190 192 8 189 191 189 190 2375 192 8 |cat Fc1=6 Fc2=4 Fc3=2 |num Fn1:0.0 Fn2:0.0 Fn3:0.0 Fn4:1.0 Fn5:0.0 Fn6:0.0 Fn7:0.0 Fn8:0.0 Fn9:0.0
1 |session 295 295 295 295 295 295 295 295 295 295 |cat Fc1=1 Fc2=4 Fc3=3 |num Fn1:1.0 Fn2:1.0 Fn3:1.0 Fn4:1.0 Fn5:1.0 Fn6:1.0 Fn7:1.0 Fn8:1.0 Fn9:1.0


In [100]:
train_part_vw_fe = os.path.join(PATH_TO_DATA2, 'train_part_fe.vw')
valid_vw_fe = os.path.join(PATH_TO_DATA2, 'valid_fe.vw')
train_vw_fe = os.path.join(PATH_TO_DATA2, 'train_fe.vw')
test_vw_fe = os.path.join(PATH_TO_DATA2, 'test_fe.vw')
model_fe = os.path.join(PATH_TO_DATA2, 'vw_model_fe.vw')
valid_pred_fe = os.path.join(PATH_TO_DATA2,'vw_valid_pred_fe.csv')
pred_fe = os.path.join(PATH_TO_DATA2, 'vw_pred_fe.csv')

In [109]:
%%time
!vw --oaa 400 --passes 5 -c -k -b 26 --loss_function logistic --random_seed 17\
    -d $train_part_vw_fe -f $model_fe --quiet
    
!vw -i $model_fe -t -d $valid_vw_fe -p $valid_pred_fe --quiet
    
    
print(f'Accuracy: {accuracy_score(y_valid_for_vw,pd.read_csv(valid_pred_fe,header=None))}')

Accuracy: 0.42857142857142855
Wall time: 7min 39s


In [102]:
%%time
!vw --oaa 400 --passes 5 -c -k -b 26 --loss_function logistic --random_seed 17\
    -d $train_vw_fe -f $model_fe --quiet
    
!vw -i $model_fe -t -d $test_vw_fe -p $pred_fe --quiet

print('Done!')

Done!
Wall time: 11min


In [104]:
df_pred_fe = pd.read_csv(pred_fe,header=None)
vw_pred_fe = class_encoder.inverse_transform(df_pred_fe - 1)
vw_pred_fe

array([628, 149, 866, ..., 371, 924, 820], dtype=int64)

In [105]:
write_to_submission_file(vw_pred_fe, os.path.join(PATH_TO_DATA2, 'vw_400_users_vw_log_fe.csv'))

Что самое странное, на лидерборде результат ухудшился сильно, при этом видно что на валидации качество существенно улучшилось.